---
name: Run commands on different operating systems
on: ['push']

jobs:
  run-tests-on-ubuntu:
    name: Run Tests on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3
      - run: python3 plugins/filters/schedule_utils.py
